version: '3.8'

services:
  sqlite-fastapi-server:
    build: ./sqlite_app
    ports:
      - "8000:8000"
    env_file:
      - ./configs/config_sqlite.env
    volumes:
      - sqlite_data:/app/data
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    env_file:
      - ./configs/config_mongo_db.env
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  mongo-fastapi-server:
    build: ./mongo_app
    ports:
      - "8001:8000"
    env_file:
      - ./configs/config_mongo_server.env
    depends_on:
      - mongodb
      - sqlite-fastapi-server
    networks:
      - app-network

  main-server:
    build: ./main_server
    ports:
      - "8002:8000"
    env_file:
      - ./configs/config_main_server.env
    depends_on:
      - mongodb
      - sqlite-fastapi-server
      - mongo-fastapi-server
    networks:
      - app-network


volumes:
  mongo_data:
    driver: local
    driver_opts:
      type: none
      device: "/Users/alicee/Desktop/Work_Main/docker_test/docker_servers/db_mongo"  # Укажите путь на хосте для MongoDB
      o: bind
  sqlite_data:
    driver: local
    driver_opts:
      type: none
      device: "/Users/alicee/Desktop/Work_Main/docker_test/docker_servers/db_sqlite"  # Укажите путь на хосте для SQLite
      o: bind
networks:
  app-network:
    driver: bridge
